title: 'iGotRoot Blog'
description: "I write about security stuff..."
baseurl: "/"
url: "https://igotroot.com"

header_pages:
  - index.md
  - about.md

style: dark

footer: 'Follow me on <a href="https://twitter.com/iGotRootBlog">Twitter</a>'

# Build settings
markdown: kramdown
theme: jekyll-theme-console
#remote_theme: b2a3e8/jekyll-theme-console
